<?php

$preamp['config']['custom_post_type']['wpep'] = array(
	'active' => true,
	'labels' => array(
		'name'               => 'WP Event Pilot',
		'singular_name'      => 'WP Event Pilot',
		'menu_name'          => _x( 'WP Event Pilot', 'admin menu', 'wpep' ),
		'name_admin_bar'     => 'WP Event Pilot',
		'add_new'            => _x( 'Add New Event', 'event', 'wpep' ),
		'add_new_item'       => __( 'Add New Event', 'wpep' ),
		'new_item'           => __( 'New Event', 'wpep' ),
		'edit_item'          => __( 'Edit Event', 'wpep' ),
		'view_item'          => __( 'View Event', 'wpep' ),
		'all_items'          => __( 'All Events', 'wpep' ),
		'search_items'       => __( 'Search Event', 'wpep' ),
		'not_found'          => __( 'No Event found.', 'wpep' ),
		'not_found_in_trash' => __( 'No Event found in Trash.', 'wpep' ),
		'featured_image'     => __( 'Event Cover', 'wpep' ),
		'remove_featured_image'  => __( 'Remove Event Cover', 'wpep' ),
		'use_featured_image'     => __( 'Use as Event Cover', 'wpep' ),
		'set_featured_image'     => __( 'Set Event Cover', 'wpep' ),
	),
	'messages' => array(
		1  => __( 'Event updated.', 'wpep' ),
		2  => __( 'Event updated.', 'wpep' ),
		3  => __( 'Event deleted.', 'wpep' ),
		4  => __( 'Event updated.', 'wpep' ),
		5  => __( 'Event restored to revision from %revision%', 'wpep' ),
		6  => __( 'Event published.', 'wpep' ),
		7  => __( 'Event saved.', 'wpep' ),
		8  => __( 'Event submitted.', 'wpep' ),
		9  => __( 'Event scheduled for: <strong>%date%</strong>.', 'wpep' ),
		10 => __( 'Event draft updated.', 'wpep' ),
	),
	'description' => __( 'Description.', 'wpep' ),
	'public' => true,
	'hierarchical' => false,
	'exclude_from_search' => false,
	'publicly_queryable' => true,
	'show_ui' => true,
	'show_in_menu' => true,
	'show_in_nav_menus' => true,
	'show_in_admin_bar' => true,
	'menu_position' => null,
	'menu_icon' => 'dashicons-admin-post',
	'capability_type' => 'post',
	// 'capabilities' => array('edit_posts'),
	// 'map_meta_cap' => false,
	'supports' => array( 'title', 'editor', 'thumbnail' ), // 'title', 'editor', 'author', 'thumbnail', 'excerpt', 'comments'
	// 'register_meta_box_cb' => true,
	// 'taxonomies' => array(),
	// 'has_archive' => false,
	'rewrite' => array( 'slug' => 'events' ),
	'query_var' => true,
	'can_export' => true,
	'delete_with_user' => true,
	'custom_menu_icon' => 'assets/images/wpep.svg',
);

$preamp['config']['admin_custom_columns']['gallery'] = array(
	'post_type' => 'wpep',
	'columns' => array(
		'featured_image',
		'title',
		'date',
	),
);
